apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: ghcr.io/mxschmitt/try-playwright/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: SITE_ADDRESS
              value: ":80"
      restartPolicy: Always
